version: "3.7"

services:
  frontend: 
    build: ./
    image: amontoa_server_front-end
    container_name: front-end
    restart: always
    command: npm start
    ports:
      - 8000:8000
    volumes:
      - storage:/urs/amontoa/frontend

volumes:
  storage:
    driver: local
    driver_opts:
      device: tmpfs
      o: size=100000,uid-1000
      type: tmpfs
